in catch, throwing exception
in finally
TypeError: blah
	at ()
	at global$init()
